name: Generate Automated Release

on:
  push:
    tags:
      - 'v*' # Triggers workflows only when a tag starting with 'v' is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to create releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history so the changelog tool can see past commits

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
